### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xtcl#1]
In order to launch we should have:

- [ ] Tcl as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [ ] at least 10 problems
- [ ] a "how to get started" topic in the [help repo](https://github.com/exercism/docs) repo (`app/pages/languages/getting-started-with-tcl.md`)
- [ ] one to a handful of people willing to check exercism regularly (daily?) for nitpicks to ensure that the track gets off on the right foot
- [ ] add track implementors and other designated nitpickers as mentors to the track
- [ ] toggle `"active"` to `true` in `config.json`

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* Each submission receives feedback quickly, preferably within the first 24 hours.
* The nitpicks do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore new aspects of the language.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md
